### PR TITLE
Add eslint

### PR DESCRIPTION
**Pull request by deathart**
Hello everyone, in advance I apologize for my English, I am French :p

I propose an integration of Eslint+Prettier !

Why?

If many dev work on the project but that each one has its own rules that may be a real site not readable!

I just made the integration, it is necessary to configure, for me it is with you to configure it with your way of seeing the things, if you wish to have a github actions which lint automatically ask me and I will set it up on this branch.

Hello from France.

### CODE REVIEW

**Comment by raflymln** [comment]
Hi! thank you for doing PR for this, actually I've tried several eslint configuration, if you don't mind, can you tell me about the rules of the eslint? is it configured to have the same code too?

**Comment by deathart** [comment]
Eslint and prettier allows you to put rules in place to have a nice code, for example an indentation of 2 spaces, line breaks between each function, etc... to have all the rules: https://eslint.org/docs/rules/

Currently only recommendation rules are active!

To know that the final output code (so once compiled) is the same, the lint is only checked on TS files.

Currently a lot of warning and error because I did not take the time to correct, because I wait that you give your rules!

**Comment by raflymln** [comment]
the warn and error is actually the things that's makes me think about it again, but i'll try it later

**Comment by raflymln** [comment]
also, thank you for your contributions 👍

**Pull request merged**
